version: '3.8'

services:
  mongo-db:
    image: mongo:latest
    container_name: madeOfiron_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: madeOfiron
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: